### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pmaier1** [owncloud/notifications#112]
## Motivation
Release needed for https://github.com/owncloud/enterprise/issues/2136 and https://github.com/owncloud/customgroups/issues/81, respectively. Also there are some merged things in the milestone.

### QA
- [ ] Create release branch
- [ ] Create "$version Testplan"
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [ ] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (#113)
- [ ] Create github tag for '$version'
- [ ] Build and sign tarball from github tag '$version'
- [ ] Upload to marketplace
- [ ] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md

**Comment by PVince81** [comment]
note: notifications is still bundled so will be released as part of 10.0.3

**Comment by patrickjahns** [comment]
now released as part of 10.0.4 - whats our take on this for unbundling it?

**Comment by VicDeo** [comment]
This app has a makefile and changelog already.
As far I understand the flow we need a release branch with version bump and  `info.xml` update that could be passed to QA

**Comment by PVince81** [comment]
I've added the step "remove from core release script" to be done once the app is published.

**Comment by PVince81** [comment]
closing this for now as it's outdated

we need to reconsider unbundling
