### ISSUE TITLE
[decouple] Notifications 0.5.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/notifications#271]
When taking care of a task (and marking as done), please add your name to the task!

### Reason

- Decouple release cycle from core

### Tasks

- [x] align master with stable10 so we can work solely on master in the future: https://github.com/owncloud/notifications/pull/270
- [x] lock stable10 branch

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [ ] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [ ] Smoke test tarball (at least install + enable)

### Publishing

- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by patrickjahns** [comment]
When comparing master and stable10 ( built be our release scripts) noticed the following diffs

```
Only in old/owncloud/apps/notifications: .drone.yml
Only in old/owncloud/apps/notifications: .phan
Only in old/owncloud/apps/notifications: .php_cs.dist
Files new/owncloud/apps/notifications/CHANGELOG.md and old/owncloud/apps/notifications/CHANGELOG.md differ
Only in old/owncloud/apps/notifications: Makefile
Only in new/owncloud/apps/notifications: README.md
Files new/owncloud/apps/notifications/appinfo/info.xml and old/owncloud/apps/notifications/appinfo/info.xml differ
Files new/owncloud/apps/notifications/appinfo/signature.json and old/owncloud/apps/notifications/appinfo/signature.json differ
Only in old/owncloud/apps/notifications: composer.json
Only in old/owncloud/apps/notifications: composer.lock
Only in new/owncloud/apps/notifications/img: notifications-dark.png
Only in new/owncloud/apps/notifications/img: notifications-dark.svg
Only in new/owncloud/apps/notifications/img: notifications-grey.png
Only in new/owncloud/apps/notifications/img: notifications-grey.svg
Only in new/owncloud/apps/notifications/img: notifications-new-dark.png
Only in new/owncloud/apps/notifications/img: notifications-new-dark.svg
Only in new/owncloud/apps/notifications/img: notifications-new-grey.png
Only in new/owncloud/apps/notifications/img: notifications-new-grey.svg
Files new/owncloud/apps/notifications/l10n/.tx/config and old/owncloud/apps/notifications/l10n/.tx/config differ
Only in new/owncloud/apps/notifications/l10n: ar.js
Only in new/owncloud/apps/notifications/l10n: ar.json
Files new/owncloud/apps/notifications/l10n/de.js and old/owncloud/apps/notifications/l10n/de.js differ
Files new/owncloud/apps/notifications/l10n/de.json and old/owncloud/apps/notifications/l10n/de.json differ
Only in new/owncloud/apps/notifications/l10n: en_GB.js
Only in new/owncloud/apps/notifications/l10n: en_GB.json
Only in new/owncloud/apps/notifications/l10n: gl.js
Only in new/owncloud/apps/notifications/l10n: gl.json
Only in new/owncloud/apps/notifications/l10n: he.js
Only in new/owncloud/apps/notifications/l10n: he.json
Only in new/owncloud/apps/notifications/l10n: ia.js
Only in new/owncloud/apps/notifications/l10n: ia.json
Only in new/owncloud/apps/notifications/l10n: is.js
Only in new/owncloud/apps/notifications/l10n: is.json
Only in new/owncloud/apps/notifications/l10n: it.js
Only in new/owncloud/apps/notifications/l10n: it.json
Only in new/owncloud/apps/notifications/l10n: ja.js
Only in new/owncloud/apps/notifications/l10n: ja.json
Only in new/owncloud/apps/notifications/l10n: mk.js
Only in new/owncloud/apps/notifications/l10n: mk.json
Only in new/owncloud/apps/notifications/l10n: nb_NO.js
Only in new/owncloud/apps/notifications/l10n: nb_NO.json
Only in new/owncloud/apps/notifications/l10n: pl.js
Only in new/owncloud/apps/notifications/l10n: pl.json
```

**Comment by PVince81** [comment]
yeah seems there are some new icons on master but not on stable10.

- [ ] need to mention in changelog and find what PR it comes from for testing

**Comment by PVince81** [comment]
ok, the PR in question for the dark icons is https://github.com/owncloud/notifications/pull/185.

I've cherry-picked this on stable10 now so the diff should be limited to translation files now @patrickjahns

**Comment by PVince81** [comment]
I've now updated the release-0.5.0 with master and included the missing PRs in the changelog: https://github.com/owncloud/notifications/commit/51c8fbc06c40f54c8252a48a7edac7cb7e3ff02b

**Comment by PVince81** [comment]
RC1: was missing changelog

RC2: build here https://github.com/owncloud/notifications/releases/tag/v0.5.0RC2

**Comment by PVince81** [comment]
Had a quick look at the diff between 10.1.1 release tarball "apps/notifications" folder and the above tarball.

The changes make sense and include stuff from the changelog and also backslash adjustments for the newer PHP versions.

**Comment by PVince81** [comment]
To test:

- [ ] TEST: notifications still work (bell icon appears, notification appears, action works). test with "accept user share"
- [ ] TEST: Added bell icon in black - [#185](https://github.com/owncloud/notifications/pull/185)
- [ ] TEST: Drop php 5.6 - [#267](https://github.com/owncloud/notifications/issues/267)
- [ ] TEST: Only set icon in case an icon is available - [#275](https://github.com/owncloud/notifications/issues/275)

**Comment by PVince81** [comment]
- [ ] BUG: broken icon when sending through occ: https://github.com/owncloud/notifications/issues/278

**Comment by PVince81** [comment]
dark icon tested by @ChrisEdS using CSS override and reported working fine with 10.2.0 and the notifications RC

**Comment by PVince81** [comment]
as https://github.com/owncloud/notifications/issues/278 is not a regression but also not trivial to resolve, let's skip it for this release

**Comment by PVince81** [comment]
final release archive: https://github.com/owncloud/notifications/releases/tag/v0.5.0
